export enum TicabankPersonality {
  LOAN_TICABANK_OK = 'YTIKABANK',

  OFFER_NO_DATA = 'YPTPLI003',
  OFFER_CALL_FAILED = 'YPTPLI004',
  OFFER_CALL_TIMEOUT = 'YPTPLI020',

  SIMULATE_NO_DATA = 'YPTPLI007',
  SIMULATE_CALL_FAILED = 'YPTPLI008',
  SIMULATE_CALL_TIMEOUT = 'YPTPLI021',

  PAYDATE_NO_DATA = 'YPTPLI011',
  PAYDATE_CALL_FAILED = 'YPTPLI012',
  PAYDATE_CALL_TIMEOUT = 'YPTPLI022',

  QUOTE_NO_DATA = 'YPTPLI015',
  QUOTE_CALL_FAILED = 'YPTPLI016',
  QUOTE_CALL_TIMEOUT = 'YPTPLI023',

  REGISTER_NO_DATA = 'YPTPLI025',
  REGISTER_CALL_FAILED = 'YPTPLI019',
  REGISTER_CALL_TIMEOUT = 'YPTPLI024',

  TICABANK_NOT_CONFIRMED = 'YPNOTCONF',
  TICABANK_INVALID_TERM = 'YPINVTERM',
  TICABANK_PRODUCT_REGISTER = 'YPPRODREG',
  TICABANK_UNABLE_LEAD = 'YPMUNABLE',
  TICABANK_LEAD_SOLD = 'YPMLDSOLD',

  TICABANK_BAD_REQUEST = 'YPMBADREQ',
  TICABANK_UNAUTHORIZED = 'YPUNAUTHZ',
  METHOD_NOT_ALLOWED = 'YPNOALLOW',
  LOAN_MANY_REQUESTS = 'YPTOOMREQ',
  TICABANK_SERVER_ERROR = 'YPSERVERR',
}
