export enum MibancoPersonality {
  LOAN_MIBANCO_OK = 'YPMIBANCO',

  OFFER_NO_DATA = 'YPTPLI003',
  OFFER_CALL_FAILED = 'YPTPLI004',
  OFFER_CALL_TIMEOUT = 'YPTPLI020',

  SIMULATE_NO_DATA = 'YPTPLI007',
  SIMULATE_CALL_FAILED = 'YPTPLI008',
  SIMULATE_CALL_TIMEOUT = 'YPTPLI021',

  PAYDATE_NO_DATA = 'YPTPLI011',
  PAYDATE_CALL_FAILED = 'YPTPLI012',
  PAYDATE_CALL_TIMEOUT = 'YPTPLI022',

  QUOTE_NO_DATA = 'YPTPLI015',
  QUOTE_CALL_FAILED = 'YPTPLI016',
  QUOTE_CALL_TIMEOUT = 'YPTPLI023',

  REGISTER_NO_DATA = 'YPTPLI025',
  REGISTER_CALL_FAILED = 'YPTPLI019',
  REGISTER_CALL_TIMEOUT = 'YPTPLI024',

  MIBANCO_NOT_CONFIRMED = 'YPNOTCONF',
  MIBANCO_INVALID_TERM = 'YPINVTERM',
  MIBANCO_PRODUCT_REGISTER = 'YPPRODREG',
  MIBANCO_UNABLE_LEAD = 'YPMUNABLE',
  MIBANCO_LEAD_SOLD = 'YPMLDSOLD',

  MIBANCO_BAD_REQUEST = 'YPMBADREQ',
  MIBANCO_UNAUTHORIZED = 'YPUNAUTHZ',
  METHOD_NOT_ALLOWED = 'YPNOALLOW',
  LOAN_MANY_REQUESTS = 'YPTOOMREQ',
  MIBANCO_SERVER_ERROR = 'YPSERVERR',
}
