---
name: QA Flow

on:
  push:
    branches: [main]

jobs:
  unit_test:
    uses: yaperos/reusable-workflows/.github/workflows/tests.yaml@main
    with:
      node_version: 20
      environment: qa
      test_command: npm test
      test_with_postgres: false
      slack_channel: notifications_qa_stg
    secrets: inherit

  code_scanner:
    uses: yaperos/reusable-workflows/.github/workflows/code_scanner.yaml@main
    needs: [unit_test]
    with:
      environment: qa
      slack_channel: notifications_qa_stg
      checkmarx_tenant: yape
      deploy_flow: true
    secrets: inherit

  build_qa:
    uses: yaperos/reusable-workflows/.github/workflows/build.yaml@main
    needs: [code_scanner]
    with:
      environment: qa
      slack_channel: notifications_qa_stg
    secrets: inherit

  deploy_qa:
    uses: yaperos/reusable-workflows/.github/workflows/deploy.yaml@main
    needs: [build_qa]
    with:
      environment: qa
      squad_name: qa
      hostname: fwkyapemocks
      slack_channel: notifications_qa_stg
    secrets: inherit

  api_integration_tests_qa:
    name: 🧪 API Integration Tests QA
    needs: [deploy_qa]
    uses: yaperos/reusable-workflows/.github/workflows/tests_qa_foundation.yaml@main
    with:
      environment: 'qa'
      test_folder: ''
      test_subfolder: ''
      slack_channel_notification_failure: '#automatech-alerts'
      test_tags: '@mocks'
      unit: 'yape3'
      domain: 'yape'
      test_command: 'cy:browserstack:pipeline'
      test_repository: 'fwk-api-test'
      artifact_name: 'mochawesome-report-QA'
      screenshots_name: 'cypress-screenshots-QA'
      notify_on_success: true
    secrets: inherit
