---
name: Release Flow

on:
  workflow_dispatch:
    inputs:
      releaseCandidateVersion:
        description: 'Name of version (ie v1.0.0-rc.0)'
        required: true

run-name: Release Flow at version ${{ github.event.inputs.releaseCandidateVersion }}

jobs:
  validate_release:
    uses: yaperos/reusable-workflows/.github/workflows/validate_release.yaml@main
    with:
      environment: stg
      version: ${{ inputs.releaseCandidateVersion }}
      slack_channel: notifications_qa_stg
    secrets: inherit

  unit_test:
    uses: yaperos/reusable-workflows/.github/workflows/tests.yaml@main
    needs: [validate_release]
    with:
      node_version: 20
      environment: stg
      test_command: npm test
      test_with_postgres: false
      slack_channel: notifications_qa_stg
    secrets: inherit

  build_stg:
    uses: yaperos/reusable-workflows/.github/workflows/build.yaml@main
    needs: [unit_test]
    with:
      environment: stg
      releaseCandidateVersion: ${{ inputs.releaseCandidateVersion }}
      slack_channel: notifications_qa_stg
    secrets: inherit

  deploy_stg:
    uses: yaperos/reusable-workflows/.github/workflows/deploy.yaml@main
    needs: [build_stg]
    with:
      environment: stg
      squad_name: qa
      hostname: fwkyapemocks
      slack_channel: notifications_qa_stg
      releaseCandidateVersion: ${{ inputs.releaseCandidateVersion }}
    secrets: inherit

  get_last_tag:
    uses: yaperos/reusable-workflows/.github/workflows/last_tag.yaml@main
    needs: [deploy_stg]
    with:
      tag: ${{ inputs.releaseCandidateVersion }}
      message: ${{ inputs.releaseCandidateVersion }}
      slack_channel: notifications_qa_stg
    secrets: inherit

  generate_pre_release:
    uses: yaperos/reusable-workflows/.github/workflows/generate_release.yaml@main
    needs: [get_last_tag]
    with:
      environment: stg
      releaseCandidateVersion: ${{ inputs.releaseCandidateVersion }}
      base_ref: ${{ needs.get_last_tag.outputs.stg_last_version }}
      slack_channel: notifications_qa_stg
    secrets: inherit
